import type { Metadata } from "next";
import {Lato} from 'next/font/google'
import "./globals.css";

import ResponsiveNavbar from "@/components/Navbar/ResponsiveNavbar";


const font = Lato({
  weight:["100","300","400","700","900"],
  subsets: ['latin','latin-ext']
})


export const metadata: Metadata = {
  title: "Landing Page Build with Tailwind and NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ResponsiveNavbar/>
        {children}
      </body>
    </html>
  );
}
